name: Build Raspberry Pi OS MIDI Image

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Clone pi-gen
        run: |
          git clone --depth=1 https://github.com/RPi-Distro/pi-gen.git

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc python3

      - name: Add custom build stage
        run: |
          mkdir -p pi-gen/stage4/01-midi-setup
          cat << 'EOF' > pi-gen/stage4/01-midi-setup/00-run.sh
          #!/bin/bash
          on_chroot << EOF2
            apt-get update
            apt-get install -y fluidsynth fluid-soundfont-gm qsynth alsa-utils chromium-browser

            # Auto-start FluidSynth as a systemd service
            cat <<EOT > /etc/systemd/system/fluidsynth.service
            [Unit]
            Description=FluidSynth MIDI Synthesizer
            After=sound.target

            [Service]
            ExecStart=/usr/bin/fluidsynth -i -a alsa -m alsa_seq /usr/share/sounds/sf2/FluidR3_GM.sf2
            Restart=always
            User=pi

            [Install]
            WantedBy=multi-user.target
            EOT

            systemctl enable fluidsynth

            # Enable SSH and VNC
            raspi-config nonint do_ssh 0
            raspi-config nonint do_vnc 0

            # Create wifi setup script
            cat <<EOW > /usr/local/bin/wifi-setup.sh
            #!/bin/bash
            echo "WLAN SSID:"
            read ssid
            echo "WLAN Passwort:"
            read -s psk
            cat <<EOT2 > /etc/wpa_supplicant/wpa_supplicant.conf
            country=DE
            ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
            update_config=1
            network={
                ssid=\"\$ssid\"
                psk=\"\$psk\"
            }
            EOT2
            wpa_cli -i wlan0 reconfigure
            EOW

            chmod +x /usr/local/bin/wifi-setup.sh
          EOF2
          EOF
          chmod +x pi-gen/stage4/01-midi-setup/00-run.sh

      - name: Build image
        run: |
          cd pi-gen
          sudo ./build.sh

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-midi-image
          path: pi-gen/deploy/*.img
